tomato: YU Doze [SQUASHED]
Change-Id: Id0849fb5c17ff569d771a19cebfc579dc93dbd59
Signed-off-by: Vibhor Chaudhary <cvibhu0009@gmail.com>

YUDoze: Add service for using proximity sensor for wake-up

* Added custom service that uses proximity sensor in wake-up mode
  to trigger display on
* If more sensor triggers are suitable to use, they can be added
  to the service

Change-Id: Id0849fb5c17ff569d771a19cebfc579dc93dbc48
Signed-off-by: Vibhor Chaudhary <cvibhu0009@gmail.com>

Conflicts:
	device.mk

YUDoze: Set gesture to disabled by default

Change-Id: I0bf3f6a3a4c01bab7ff7522e916e2149f9cfe8d5
Signed-off-by: Vibhor Chaudhary <cvibhu0009@gmail.com>

YUDoze: Consolidate doze settings

* Allow user to disable ambient display from gesture panel
* Disable/enable doze settings based on ambient display state

Change-Id: I0ff7686ccc04037b3ada9a8355384ba6746cf30c
Signed-off-by: Vibhor Chaudhary <cvibhu0009@gmail.com>

YUDoze: fix defaults

Change all defaults to false

Change-Id: I2df507b2fc823d3fb07bce89d44067db565a5ab8
Signed-off-by: Vibhor Chaudhary <cvibhu0009@gmail.com>

YUDoze: Add back button to action bar

Change-Id: Ia56183c8c2d5a6bc25c84f1d1b9823b84bc936c9
Signed-off-by: Vibhor Chaudhary <cvibhu0009@gmail.com>

YUDoze: add proximity wake

Change-Id: Ib02f4611e7b8bc09d540ca5c49aab68ef27f188b
Signed-off-by: Vibhor Chaudhary <cvibhu0009@gmail.com>

YUDoze: restore proximity wake preference on boot

Change-Id: I614772d6ff1005968a7f8f1ed0349e3878ddadf1
Signed-off-by: Vibhor Chaudhary <cvibhu0009@gmail.com>

YUDozeService: Prevent a pm wakeup with a timestamp in the future

Prevents:

java.lang.IllegalArgumentException: event time must not be in the future
at android.os.Parcel.readException(Parcel.java:1550)
        at android.os.Parcel.readException(Parcel.java:1499)
        at android.os.IPowerManager$Stub$Proxy.wakeUp(IPowerManager.java:550)
        at android.os.PowerManager.wakeUp(PowerManager.java:666)
        at com.cyanogenmod.settings.device.SamsungDozeService$SamsungProximitySensor.shouldPulse(SamsungDozeService.java:95)
        at com.cyanogenmod.settings.device.SamsungDozeService$SamsungProximitySensor.onSensorChanged(SamsungDozeService.java:75)
        at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:405)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:143)
        at android.os.Looper.loop(Looper.java:122)
        at android.app.ActivityThread.main(ActivityThread.java:5289)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

Change-Id: I8ed248271d67216e531b124bf27101fa538f1195
Signed-off-by: Vibhor Chaudhary <cvibhu0009@gmail.com>

YUDozeService: properly fix future timestamp error

Previously attempted fix at review.cyanogenmod.org/#/c/104083/
The timestamp isn't in the future, that would be impossible.
The real issue is the timestamp from the SensorEvent is a true
timestamp, the System.nanoTime is nanoseconds since boot.
So the previous patch would always return false and never pulse.
I've simply changed it so that the wakeup call gets sent the current
System.nanoTime in milliseconds since boot so it does not think the
event came from the future since the wakeUp method expects
uptimeMillis, not true world time.

Change-Id: I78f5e9d61107caf9c3bf6c10fa7c5bb400082294
Signed-off-by: Vibhor Chaudhary <cvibhu0009@gmail.com>

YUDoze: fix typo

Change-Id: Id7716387688080b5ce0a99a4d968e210d8eed6f9
Signed-off-by: Vibhor Chaudhary <cvibhu0009@gmail.com>

YUDOze: Remove summary for YUDoze

* Doesn't look good

Change-Id: Iaddc0758e0af63e7989b5fe2df581cccbc3d5bcc
Signed-off-by: Vibhor Chaudhary <cvibhu0009@gmail.com>